
volumes:
  media: null
  pg_data: null
  static: null

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: klinicwork/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: klinicwork/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: klinicwork/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
